version: "3.7"

services:
   poster-db:
      image: postgres:alpine
      container_name: poster-db
      ports:
         - 8003:5432
      environment:
         POSTGRES_PASSWORD: KQYsG4Hi201ajyEzOSGzr4MVfw==
      networks:
         - poster-db-network
      volumes:
         - poster-db-data:/var/lib/postgresql/data
      restart: always

   poster-redis:
      image: redis:alpine
      container_name: poster-redis
      ports:
         - 9999:6379
      networks:
         - poster-redis-network
      volumes:
         - poster-redis-data:/data
      restart: always

   poster-admin:
      container_name: poster-admin
      build:
         context: ./admin
         dockerfile: ./Dockerfile
      ports:
         - 8002:80
      volumes:
         - ./admin:/var/www/html
      networks:
         - poster-db-network
         - poster-redis-network
      restart: always

   poster-frontend:
      container_name: poster-frontend
      build:
         context: ./frontend
         dockerfile: ./Dockerfile
      ports:
         - 8001:80
      volumes:
         - ./frontend:/var/www/html
      restart: always

networks:
   poster-db-network:
      external: true
   poster-redis-network:
      external: true

volumes:
   poster-db-data:
   poster-redis-data:
